# review for PRs
name: SpaceONE Review

on:
  pull_request:
    branches:
      - release
jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        echo "Dummy build job ..."

    - name: Test
      id: test
      run: |
        echo "Running test ... None"
        # fail test or pass test
